### ISSUE TITLE
Change layout of geofunn page

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#141]
We experience that the design of the geofunn page does not work. It always cuts off the important part as the central lower part is covered:
![screen shot 2015-04-22 at 19 37 46](https://cloud.githubusercontent.com/assets/7487883/7281033/5021df8a-e927-11e4-9e25-c764c41d7d24.png)
So we need to change this and move the picture up so that this part is white and the picture begins on top of it:
![screen shot 2015-04-22 at 19 37 55](https://cloud.githubusercontent.com/assets/7487883/7281050/6e534c6e-e927-11e4-82fc-0b11a412b80c.png)

Is that possible?

**Comment by diplomod** [comment]
Same here:
![screen shot 2015-04-27 at 17 04 14](https://cloud.githubusercontent.com/assets/7487883/7350432/81e2d9a8-ecff-11e4-8f82-dcc8db1dd616.png)
http://dokuhl.de/nordryggen/about/

**Comment by bokiftw** [comment]
OK, I did this. Since this is relative to photo, and how it looks like (dimensions and amount of sky) you will se if this fits fine. Maybe some picture will fit better than other, so we need to find a middle. I guess I made enough improvements to fit better.

**Comment by diplomod** [comment]
great. looking forward to see the changes.

**Comment by diplomod** [comment]
Eiher we have a misunderstanding or this went wrong:
![screen shot 2015-04-30 at 15 53 15](https://cloud.githubusercontent.com/assets/7487883/7414167/1b04ee02-ef51-11e4-8cd5-19a812d2f6f1.png)
Now the picture is still behind the white space behind title, and in addition, the avatar looks terrible now.

It should look like this:
![unbenannt](https://cloud.githubusercontent.com/assets/7487883/7414276/f1344266-ef51-11e4-9667-e45a3c544172.png)
More boring, but works.

**Comment by bokiftw** [comment]
Oh okay, I didn't get you were thinking of these. I just tried to pull image upper, so it's upper part will be shown more. I hoped it will be better but if you don't agree okay, I will make it like this.

**Comment by diplomod** [comment]
Wel, we need to show the entire picture. And the profile picture + name looks very strange at the moment.
So as I drafted it in my last comment, please.

**Comment by bokiftw** [comment]
Yeah, no problem. I will pull this down and profile image is damaged while merging. I need to see this with Lukas. I have sent him an email to try to organise.

**Comment by diplomod** [comment]
The update came to work now. Thank you!

3 things we need to change still - this is extremely important:

1) Most of the pictures have the most important part in the center or at the bottom. At the moment, it seems as is the pictures are oriented at the top, meaning the part at the bottom is always cut off. This spoils most of the pictures (just as it did before with the white part before).
Can you orient the picture in the center?

Like this I mean:
![folie1](https://cloud.githubusercontent.com/assets/7487883/7517801/66570332-f4d7-11e4-8b29-3ccd6985dcb4.jpg)
![folie2](https://cloud.githubusercontent.com/assets/7487883/7517805/66892d4e-f4d7-11e4-84ef-c29549e7861b.jpg)
![folie3](https://cloud.githubusercontent.com/assets/7487883/7517803/668670ae-f4d7-11e4-843f-a75ff54d1e1a.jpg)
![folie4](https://cloud.githubusercontent.com/assets/7487883/7517804/6687ce22-f4d7-11e4-9c7d-50ad9c053042.jpg)

Eventually then we could also go back to the design from before. Anyway, the most important thing is that you can actually see what is on the pictures!

2) On a normal laptop, I only see the picture now. We should show the headline though so that people realize that there is information below.
This is how it looks now:
![screen shot 2015-05-07 at 13 54 47](https://cloud.githubusercontent.com/assets/7487883/7514794/184b0b4a-f4c1-11e4-8df5-baf3c6a783dd.png)
This is how much of the headline I would like to show (but with the header of course):
![screen shot 2015-05-07 at 13 56 38](https://cloud.githubusercontent.com/assets/7487883/7514798/2192ea74-f4c1-11e4-8720-67742a3cffc9.png)

3) The intro text seems to be cut off on the right hand side, maybe that is because of the sponsor logo?
![screen shot 2015-05-07 at 13 54 40](https://cloud.githubusercontent.com/assets/7487883/7514760/ca0d3746-f4c0-11e4-837c-2352c0efd957.png)

**Comment by diplomod** [comment]
That's particularly difficult for geofunn without a picture:
![screen shot 2015-05-07 at 14 39 22](https://cloud.githubusercontent.com/assets/7487883/7515398/f54738ac-f4c6-11e4-942d-a52c06a38f0f.png)

**Comment by bokiftw** [comment]
I have edited this. You can take a look at out staging server. This is the best way and most optimal how this can look like.
Honestly, you are trying to put too much content in a position (topper + banner + nav + slider/image + heading). This can be very tricky and very bad on smaller screens. So I am not sure whats the optimal other than this, since we are making it very similar to before.. take a look.

**Comment by diplomod** [comment]
Thank you. I will have a look when it is on the other server withh all the content.
Looks good on staging server. But the headline is not visible either (see point 2 above):

![screen shot 2015-05-07 at 17 36 17](https://cloud.githubusercontent.com/assets/7487883/7519358/bfcbdee8-f4e0-11e4-8214-01b950d860be.png)

Re too much content: I agree. The banner on home is only for very special occasions. It will not be used very often.
The other content we can maybe reduce for mobile devices. I will think about it.
Is it possible to tell the system to never show the banner for mobile (Smartphone + Tablet)?

And eventually for
- Smartphone: Title + button only (no intro, no coordinates)
- Tablets: Title, button + Intro (no coordinates)
  etc?

**Comment by bokiftw** [comment]
Okay, I will pull up heading a little bit more and make home banner not visible on mobile.

**Comment by diplomod** [comment]
Very good. Can you also disable intro on smartphone?

**Comment by bokiftw** [comment]
yes, I will also make changes like you sad in these to points. (if you meant that intro?)

**Comment by diplomod** [comment]
thanks - see also new #172

**Comment by bokiftw** [comment]
I have done this. I think issue is fixed now and works fine on dokuhl server.

**Comment by diplomod** [comment]
@bokiftw Thank you. I am afraid though that we need to change strategy here because it is still not working for many pictures - unfortunately. 
I have discussed with @lukassiedel right now and we has an idea. Would you be available today for some questions, if we need your input?
